### ISSUE TITLE
Failed sending metrics

### ISSUE THREAD

**Issue by aguetkriegerisch** [TheDutchMC/SkinFixer#10]
Hi, Looking at the console, I noticed that occasionally I get this error related to metrics

I hope this will help

15.06 15:59:00 [Server] PluginStatThread609397/INFO [15:59:00][DEBUG][HttpLib] HttpRequest: POST::https://plugin-stat.k8s.array21.dev/report
15.06 15:59:00 [Server] PluginStatThread609397/INFO [15:59:00][DEBUG][HttpLib] HttpRequest: 502::Bad Gateway
15.06 15:59:00 [Server] PluginStatThread609397/INFO [15:59:00][DEBUG][HttpLib] HttpRequest ErrorStream: 
15.06 15:59:00 [Server] PluginStatThread609397/WARN java.io.IOException: Server returned HTTP response code: 502 for URL: https://plugin-stat.k8s.array21.dev/report
15.06 15:59:00 [Server] PluginStatThread609397/WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
15.06 15:59:00 [Server] PluginStatThread609397/WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
15.06 15:59:00 [Server] PluginStatThread609397/WARN at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
15.06 15:59:00 [Server] PluginStatThread609397/WARN at nl.thedutchmc.httplib.Http.makeRequest(Http.java:104)
15.06 15:59:00 [Server] PluginStatThread609397/WARN at dev.array21.pluginstatlib.PluginStat$1.run(PluginStat.java:38)
15.06 15:59:00 [Server] PluginStatThread609397/WARN at java.base/java.lang.Thread.run(Thread.java:831)
15.06 15:59:00 [Server] PluginStatThread609397/WARN Failed to send metrics.

**Comment by aguetkriegerisch** [comment]
![image](https://user-images.githubusercontent.com/39163176/122117164-2617c500-cdec-11eb-8dea-da097c7609d8.png)
sorry, i tried to send you a tip, but common funds are not allowed in mexico :c

**Comment by TheDutchMC** [comment]
Hi there, thanks for opening an issue!

The metrics server is having the occasional issues due to a couple of mysql errors, working on this. Should be fixed ASAP (Until then, it is nothing to worry about!)

Thanks for wanting to send a tip! I really appreciate it! I wouldn't know how to get around that issue though, unfortunately

**Comment by aguetkriegerisch** [comment]
thanks for your amazing and hard work

**Comment by TheDutchMC** [comment]
Keeping this open for now in case other people run into this issue (which they probably will) 😅

**Comment by TheDutchMC** [comment]
Metrics API seems to be running fully stable. closing this issue then
