### ISSUE TITLE
Delete useless login messages 

### ISSUE THREAD

**Issue by hilltty** [TheDutchMC/SkinFixer#12]
**Is your feature request related to a problem? Please describe.**
When logging into the server, messages about the installation of the skin are displayed, I think they are useless  

**Describe the solution you'd like**
Empty chat at login 

**Describe alternatives you've considered**
Config setting to disable this

**Comment by TheDutchMC** [comment]
Yup can definitely add that

**Comment by TheDutchMC** [comment]
Feature is now live in [v1.6.0](https://github.com/TheDutchMC/SkinFixer/releases/tag/1.6.0) :D
