### ISSUE TITLE
 java.lang.NumberFormatException: For input string: "The ID of the channel to listen on here"

### ISSUE THREAD

**Issue by leoxs22** [TheDutchMC/SkinFixer#14]
**Describe the bug**
The default config file produces an error in

```
discordSettings:
    token: 'your secret bot token here'
    channelId: The ID of the channel to listen on here
```

It can parse the channel. 

That config should be all comment, or it shouldn't be trying to parse it if discord is set to false.

**To Reproduce**
1. Copy the jar in the plugins folder
2. Start the server

**Comment by TheDutchMC** [comment]
Good catch, thanks!
