### ISSUE TITLE
No action on command calls [SF 1.7.3; MC 1.18]

### ISSUE THREAD

**Issue by DareFox** [TheDutchMC/SkinFixer#22]
New version now plugin is broken down completely. It doesn't respond on any comamnd

Console:
![WindowsTerminal_yKFBWVEYBH](https://user-images.githubusercontent.com/47672780/144715510-378e3c0d-da25-4105-bae1-0dd26f538b24.png)

Client POV:

https://user-images.githubusercontent.com/47672780/144716010-c3615065-1770-4634-8fd3-7ce0a1584e8b.mp4

**Comment by TheDutchMC** [comment]
SkinFixer does not support plugin reloading like that I dont think. Does a restart fix your issue?

**Comment by DareFox** [comment]
Nope, full server restart doesn't fix this

**Comment by TheDutchMC** [comment]
Do you see any errors in your console? As your video does show some of the SkinFixer commands working.

**Comment by DareFox** [comment]
There is! 

![WindowsTerminal_NTFapmmdTz](https://user-images.githubusercontent.com/47672780/144745225-a7b95e56-f83d-47bf-b42d-6ec322e89b03.png)
![WindowsTerminal_jMfCOdBe3w](https://user-images.githubusercontent.com/47672780/144745229-f6993df5-59de-4bf9-9f20-b38134e7f096.png)

Seems that Rust library is the problem.
Oh, and the MC version is 1.18

**Comment by DareFox** [comment]
By the way, on Windows machine plugin is working normally

**Comment by TheDutchMC** [comment]
What operating system, architecture and OS version are you using?

**Comment by DareFox** [comment]
![изображение](https://user-images.githubusercontent.com/47672780/144746580-e091b702-9811-4a3d-bb92-a0e27fb208b2.png)

**Comment by DareFox** [comment]
> Do you see any errors in your console? As your video does show some of the SkinFixer commands working.
> 
> I'd also like to know what Minecraft version you are playing on 😃

If you mean this SkinFixer messages in chat, it was previous version of SkinFixer (1.7.2)
After reloading, it loads 1.7.3 version which was demonstrated in video

![изображение](https://user-images.githubusercontent.com/47672780/144746830-f94ab08e-3e5f-4f14-8f04-6a56a18696a5.png)

**Comment by TheDutchMC** [comment]
Fixed in v1.7.4
