### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by idannez** [TheDutchMC/SkinFixer#24]
05.12 17:54:58 [Server] WARN Exception in thread "SkinFixer UpdateChecker Thread" java.lang.IllegalStateException: zip file closed
05.12 17:54:58 [Server] WARN at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
05.12 17:54:58 [Server] WARN at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
05.12 17:54:58 [Server] WARN at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
05.12 17:54:58 [Server] WARN at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
05.12 17:54:58 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
05.12 17:54:58 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
05.12 17:54:58 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
05.12 17:54:58 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
05.12 17:54:58 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
05.12 17:54:58 [Server] WARN at SkinFixer-1.7.3-RELEASE.jar//dev.array21.httplib.Http.makeRequest(Http.java:119)
05.12 17:54:58 [Server] WARN at SkinFixer-1.7.3-RELEASE.jar//dev.array21.skinfixer.updatechecker.UpdateChecker.checkUpdate(UpdateChecker.java:34)
05.12 17:54:58 [Server] WARN at SkinFixer-1.7.3-RELEASE.jar//dev.array21.skinfixer.SkinFixer$1.run(SkinFixer.java:49)
05.12 17:54:58 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

Im not sure whats going on

**Comment by TheDutchMC** [comment]
Does this always happen when you start your server?

**Comment by idannez** [comment]
It happens with the last version, i tried with the one before and it works

**Comment by TheDutchMC** [comment]
That's definitely odd. Do you see any other errors? E.g an UnsatisfiedLinkException

**Comment by idannez** [comment]
Nothing else, just that

**Comment by TheDutchMC** [comment]
Fixed in v1.7.4
