### ISSUE TITLE
Plugin Problem

### ISSUE THREAD

**Issue by ZuM22** [TheDutchMC/SkinFixer#25]
Hello! i just saw 1.18 update for your skin plugin. But for some reason it wont work for me. i freshly instaled it on my server (never had it before), and after restart it showed it on plugin list, but wont execute any command within saying there is an internal error.. I am using 1.18 Paper Spigot version on Apex Hosting. Is it that it wont work for Paper spigot? or is it something else? Like i said i never used this plugin and i dont have any earlier versions instaled.

Console log screenshots:
https://prnt.sc/2205lr6
https://prnt.sc/2205ohu
https://prnt.sc/2205sel
https://prnt.sc/2205xj1

If there is any way to fix this problem or if i didnt set it up correctly, please reply to me as soon as possible. Thank you very much!

ZuM22 (Alex)

**Comment by TheDutchMC** [comment]
Hey there, Thanks for reporting this bug!

You're not the first, so I think this is an issue on my side.

I need to know the following:
- Which OS are you on (e.g Ubuntu)
- Which version of your OS are you on (e.g 20.04)
- Which architecture are you on (e.g x86_64)
Thanks!

**Comment by TheDutchMC** [comment]
Fixed in v1.7.4
