### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by Calcetinlol** [TheDutchMC/SkinFixer#26]
[Server] INFO org.bukkit.command.CommandException: Cannot execute command 'skin' in plugin SkinFixer v1.7.3 - plugin is disabled.
07.12 00:17:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 00:17:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 00:17:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2267) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2078) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2059) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-55]
07.12 00:17:19 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

Idk why this happend, the plugin is on, and i restarted so many times and keep saying that
when i run the command it says an internal error occurred while attempting to perform this command
that happends on a apexhosting 1.18 paper

**Comment by TheDutchMC** [comment]
Hi,

Which version of SkinFixer are you using? At startup, are there any errors when skinfixer is loaded? This is likely the reason the plugin is disabled

**Comment by Calcetinlol** [comment]
Hello

Im using the 1.7.3 version of SkinFixer, when it starts the server the console says

07.12 13:16:48 [Server] INFO [SkinFixer] Enabling SkinFixer v1.7.3
07.12 13:16:48 [Server] INFO [SkinFixer] Welcome to SkinFixer version 1.7.3 by TheDutchMC!
07.12 13:16:48 [Server] WARN [SkinFixer] Failed to load libskinfixer. Please open an issue at https://github.com/TheDutchMC/SkinFixer/issues and include your OS, architecture and SkinFixer version. Thanks!
07.12 13:16:48 [Server] WARN [SkinFixer] java.lang.UnsatisfiedLinkError: /tmp/libskinfixer9107353869417561160/libskinfixer.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/libskinfixer9107353869417561160/libskinfixer.so)
07.12 13:16:48 [Server] INFO at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
07.12 13:16:48 [Server] INFO at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
07.12 13:16:48 [Server] INFO at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
07.12 13:16:48 [Server] INFO at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
07.12 13:16:48 [Server] INFO at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
07.12 13:16:48 [Server] INFO at java.base/java.lang.Runtime.load0(Runtime.java:755)
07.12 13:16:48 [Server] INFO at java.base/java.lang.System.load(System.java:1953)
07.12 13:16:48 [Server] INFO at SkinFixer-1.7.3-RELEASE.jar//dev.array21.skinfixer.storage.LibWrapper.<clinit>(LibWrapper.java:66)
07.12 13:16:48 [Server] INFO at SkinFixer-1.7.3-RELEASE.jar//dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:55)
07.12 13:16:48 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
07.12 13:16:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
07.12 13:16:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
07.12 13:16:48 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
07.12 13:16:48 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
07.12 13:16:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
07.12 13:16:48 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
07.12 13:16:48 [Server] INFO [SkinFixer] libskinfixer loaded.
07.12 13:16:48 [Server] ERROR Error occurred while enabling SkinFixer v1.7.3 (Is it up to date?)
07.12 13:16:48 [Server] INFO java.lang.UnsatisfiedLinkError: 'void dev.array21.skinfixer.storage.LibSkinFixer.init(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)'
07.12 13:16:48 [Server] INFO at dev.array21.skinfixer.storage.LibSkinFixer.init(Native Method) ~[SkinFixer-1.7.3-RELEASE.jar:?]
07.12 13:16:48 [Server] INFO at dev.array21.skinfixer.storage.LibWrapper.init(LibWrapper.java:137) ~[SkinFixer-1.7.3-RELEASE.jar:?]
07.12 13:16:48 [Server] INFO at dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:56) ~[SkinFixer-1.7.3-RELEASE.jar:?]
07.12 13:16:48 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 13:16:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 13:16:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 13:16:48 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-55]
07.12 13:16:48 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
07.12 13:16:48 [Server] INFO [SkinFixer] Disabling SkinFixer v1.7.3
07.12 13:16:48 [Server] INFO Running delayed init tasks
07.12 13:16:48 [Server] Startup Done (7.675s)! For help, type "help"
07.12 13:16:48 [Server] INFO Timings Reset
07.12 13:16:49 [Server] WARN Exception in thread "SkinFixer UpdateChecker Thread" java.lang.IllegalStateException: zip file closed
07.12 13:16:49 [Server] WARN at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
07.12 13:16:49 [Server] WARN at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
07.12 13:16:49 [Server] WARN at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
07.12 13:16:49 [Server] WARN at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
07.12 13:16:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
07.12 13:16:49 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
07.12 13:16:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
07.12 13:16:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
07.12 13:16:49 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
07.12 13:16:49 [Server] WARN at SkinFixer-1.7.3-RELEASE.jar//dev.array21.httplib.Http.makeRequest(Http.java:119)
07.12 13:16:49 [Server] WARN at SkinFixer-1.7.3-RELEASE.jar//dev.array21.skinfixer.updatechecker.UpdateChecker.checkUpdate(UpdateChecker.java:34)
07.12 13:16:49 [Server] WARN at SkinFixer-1.7.3-RELEASE.jar//dev.array21.skinfixer.SkinFixer$1.run(SkinFixer.java:49)
07.12 13:16:49 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TheDutchMC** [comment]
Thanks. This issue is fixed in v1.7.4 which you can find [here](https://github.com/TheDutchMC/SkinFixer/releases/tag/1.7.4)
