### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by rakzoser** [TheDutchMC/SkinFixer#27]
hi, i just got error while was trying to compile skin fixer.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/82242062/146778107-01b3ee44-5c3d-476a-80cd-3c275c3fb8d7.png">
Would be very grateful if you will help me.
Prob thats problem in skinfixer api or smt like that

**Comment by TheDutchMC** [comment]
Hi there!

Thanks for showing interest in SkinFixer, it means a lot!

The deprecated API used in SkinChangeHandler is [this one](https://github.com/TheDutchMC/BukkitReflectionUtil/blob/master/src/main/java/dev/array21/bukkitreflectionlib/ReflectionUtil.java#L74) and is there to maintain backwards compatibility. However this should not cause the project for fail compilation. 

Are you using `javac`, your IDE, Gradle or the Makefile to compile SkinFixer?

**Comment by rakzoser** [comment]
Thank you for helping.
 I had opened build gradle file through IDEA Intellij
Should i try with javac

**Comment by rakzoser** [comment]
Idk, i just tried the gradle but it doesnt work too

**Comment by rakzoser** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/82242062/146794582-2e204092-8f8d-4ae4-bb1b-77284eecc47c.png">
this is the lines with API

**Comment by TheDutchMC** [comment]
Does it produce an error, or just a warning? The deprecation line is a warning for me, it compiles just fine.

Preferably you should use the Makefile, you might have to use WSL for this though. Otherwhise use the `gradlew.bat` wrapper.

**Comment by rakzoser** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/82242062/146797910-d6dd1dda-8dc6-48ed-b3ab-a0318a6688e8.png">
Getting this and it says that built successful but it doesn't create the jar file

**Comment by TheDutchMC** [comment]
You'll want to use `gradlew.bat build` from `cmd.exe`, this will create a JAR file at `./build/libs/`.

**HOWEVER**
This is not a functional jar, as it does not contain `libskinfixer.dll`, which is required to run SkinFixer. For this you'll need to run the `Makefile` using GNU Make, or do what it does manually.

**Comment by rakzoser** [comment]
I ran a Makefile and got this jar
<img width="633" alt="image" src="https://user-images.githubusercontent.com/82242062/146801865-498c48e4-50ff-40d4-a8f7-920368a53cbb.png">
But it doesnt work
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/82242062/146801907-269261a6-6faa-4c31-99d7-4d8a4872ca89.png">

**Comment by TheDutchMC** [comment]
That jar seems oddly small. My dev builds are 83MB:
![image](https://user-images.githubusercontent.com/28569170/146802822-4e873749-4e92-4e9a-9e8e-cdbe6780af44.png)

The error confirms my suspicion that `libskinfixer` is not compiled and included. When you open the JAR in e.g WinRar, does it show the folders `x86_64`, `aarch64` and `armhf`? These are the folders where `libskinfixer` lives.

Are you looking to get a build of the current master branch? If so, I can provide this here too.

**Comment by rakzoser** [comment]
Thanks, solved problem.

**Comment by TheDutchMC** [comment]
Awesome! 

What solution did you end up with? Then I can include that in building documentation

**Comment by rakzoser** [comment]
First of all,  I had to rename the Makefile to Makefile.bat. opened it and just copied x86_64, aarch64, armhf to compiled .jar file using winrar
