### ISSUE TITLE
Got httpRequest: 404::notFound in console using /setskin <code>

### ISSUE THREAD

**Issue by aguetkriegerisch** [TheDutchMC/SkinFixer#9]
When i used /setskin <code> command, plugin writes 'fetching skin value and signature...' but nothing happens

1 Tried command: /getcode https://minesk.in/1963145274 and it returns code  properly
2 when using /setskin <code_returned_above> nothing happens

- [Server] Server thread/INFO Aguet issued server command: /getcode https://minesk.in/645610566
- [Server] Server thread/INFO CONSOLE issued server command: /list 
- [Server] Server thread/INFO adm: Aguet, aguetkriegerisch
- [Server] Server thread/INFO Aguet issued server command: /setskin 715715 false
- [Server] Craft Scheduler Thread - 6/INFO [12:59:15][DEBUG][HttpLib] HttpRequest: GET::https://skinfixer.k8s.array21.dev/generate/url/aHR0cHM6Ly9taW5lc2suaW4vNjQ1NjEwNTY2
-[Server] Craft Scheduler Thread - 6/INFO [12:59:15][DEBUG][HttpLib] HttpRequest: 404::Not Found
- [Server] Craft Scheduler Thread - 6/WARN Plugin SkinFixer v1.5.1 generated an exception while executing task 39
- [Server] INFO java.lang.NullPointerException: null
- [Server] INFO at java.io.Reader.<init>(Reader.java:167) ~[?:?]
- [Server] INFO at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:?]
- [Server] INFO at nl.thedutchmc.httplib.Http.makeRequest(Http.java:110) ~[?:?]
- [Server] INFO at nl.thedutchmc.SkinFixer.apis.SkinFixerApi.getSkin(SkinFixerApi.java:24) ~[?:?]
- [Server] INFO at nl.thedutchmc.SkinFixer.changeSkin.SkinChangeHandler$1.run(SkinChangeHandler.java:46) ~[?:?]
- [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
15.06 12:59:15 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
15.06 12:59:15 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
15.06 12:59:15 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
15.06 12:59:15 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
15.06 12:59:20 [Server] Server thread/INFO CONSOLE issued server command: /list

**Comment by aguetkriegerisch** [comment]
also tried with skins from https://www.minecraftskins.com/

**Comment by TheDutchMC** [comment]
Hey there, thanks for opening an issue!

SkinFixer was never designed to pull skins from MineSkin or MinecraftSkins. You can however use `/getskin <direct image URL>`


E.g for the Skin you posted above:
1. `/getskin http://textures.minecraft.net/texture/94eb8e341f85ed78d6802900adeee77a715ce2697733656e41464107db2534d1` The URL was copied from the `Texture URL` field [here](https://minesk.in/645610566)
2. /setskin <code>` where `<code` will be returned by the `/getskin` command

However I just noticed while checking this that the SkinFixer seems to have a bug, resolving this right now.

**Comment by TheDutchMC** [comment]
The bug in the API has now been resolved, the steps above work now :D

**Comment by TheDutchMC** [comment]
Any image hosting is fine really. Mineskin works too, as it provides a direct link to the texture.

You could also use Discord (Which is what I do personally), thought if your Minecraft server isn't associated with a Discord that might be tricky.

**Comment by aguetkriegerisch** [comment]
ok using the textureurl it seems to work properly, thanks!

**Comment by TheDutchMC** [comment]
Awesome!
